import crypto from "node:crypto";
import { and, desc, eq, sql } from "drizzle-orm";
import { z } from "zod";
import { adminAuditEvents, adminBanners, adminCategories, adminPromotions, catalogProducts, inventoryAdjustments, orders, users } from "../drizzle/schema";
import { collections as seedCollections, products as seedProducts } from "../client/src/lib/catalog";
import { getDb } from "./db";
import { appEnvironment } from "./env";
import { currentUser, requireSession, setSession, type SessionUser } from "./auth";
import { badRequest, unauthorized } from "./security";
import { createUploadUrl } from "./storage";
import type { Express, Request, Response } from "express";

export const roles = ["owner", "admin", "staff"] as const;
export type AdminRole = (typeof roles)[number];
const allRoles: AdminRole[] = ["owner", "admin", "staff"];
export const rolePermissions: Record<AdminRole, Record<string, boolean>> = {
  owner: { dashboard: true, products: true, categories: true, inventory: true, promotions: true, banners: true, orders: true, customers: true, staff: true, audit: true, settings: true },
  admin: { dashboard: true, products: true, categories: true, inventory: true, promotions: true, banners: true, orders: true, customers: true, staff: false, audit: true, settings: true },
  staff: { dashboard: true, products: true, categories: false, inventory: true, promotions: false, banners: false, orders: true, customers: true, staff: false, audit: true, settings: false },
};

export function hasAdminPermission(role: AdminRole, permission: string) { return rolePermissions[role]?.[permission] === true; }

export type AdminProduct = {
  id: string; slug: string; name: string; pricePkr: number; stock: number; status: string; category: string; collection: string;
  description: string; images: string[]; tags: string[]; featured: boolean; availability: "in-stock" | "low-stock" | "out-of-stock";
};
export type AdminCategory = { id: string; slug: string; name: string; description: string; imageUrl: string; status: string; sortOrder: number };
export type AdminPromotion = { id: string; name: string; description: string; discountType: "percentage" | "fixed"; discountValue: number; targetType: "catalog" | "category" | "product"; targetValue: string; startAt: string | null; endAt: string | null; status: "draft" | "scheduled" | "active" | "ended" };
export type AdminBanner = { id: string; imageUrl: string; title: string; subtitle: string; ctaText: string; destination: string; startAt: string | null; endAt: string | null; status: "draft" | "scheduled" | "active" | "ended"; sortOrder: number };
export type AdminAudit = { id: string; actorUserId: string; actorRole: AdminRole; action: string; resource: string; resourceId: string | null; changedFields: Record<string, unknown>; requestId: string | null; createdAt: string };

type AdminState = { products: AdminProduct[]; categories: AdminCategory[]; promotions: AdminPromotion[]; banners: AdminBanner[]; adjustments: Array<Record<string, unknown>>; audit: AdminAudit[] };
const state: AdminState = {
  products: seedProducts.map((product) => ({ id: product.id, slug: product.slug, name: product.name, pricePkr: product.price, stock: product.availability === "low-stock" ? 4 : 20, status: "active", category: product.category, collection: product.collection, description: product.description, images: product.images, tags: product.tags, featured: product.tags.includes("best-seller"), availability: product.availability })),
  categories: Array.from(new Map(seedProducts.map((product) => [product.category, product.category])).keys()).map((name, index) => ({ id: `cat-${index + 1}`, slug: name.toLowerCase().replace(/[^a-z0-9]+/g, "-"), name, description: `The ${name.toLowerCase()} edit.`, imageUrl: seedCollections.find((item) => item.name.toLowerCase() === name.toLowerCase())?.image ?? seedCollections[0]?.image ?? "", status: "active", sortOrder: index })),
  promotions: [], banners: [], adjustments: [], audit: [],
};

const productSchema = z.object({
  name: z.string().trim().min(2).max(255), slug: z.string().trim().regex(/^[a-z0-9]+(?:-[a-z0-9]+)*$/).max(191), pricePkr: z.coerce.number().int().nonnegative().max(10_000_000), stock: z.coerce.number().int().nonnegative().max(1_000_000),
  category: z.string().trim().min(1).max(128), collection: z.string().trim().min(1).max(128), description: z.string().trim().min(10).max(2000), images: z.array(z.string().url()).max(8).default([]), tags: z.array(z.string().trim().min(1).max(64)).max(20).default([]), featured: z.boolean().default(false), status: z.enum(["active", "draft", "archived"]).default("active"),
});
const categorySchema = z.object({ slug: z.string().trim().regex(/^[a-z0-9]+(?:-[a-z0-9]+)*$/).max(191), name: z.string().trim().min(2).max(255), description: z.string().trim().max(1000).default(""), imageUrl: z.string().url().or(z.literal("")).default(""), status: z.enum(["active", "draft", "archived"]).default("active"), sortOrder: z.coerce.number().int().min(0).max(10000).default(0) });
const promotionSchema = z.object({ name: z.string().trim().min(2).max(255), description: z.string().trim().max(1000).default(""), discountType: z.enum(["percentage", "fixed"]), discountValue: z.coerce.number().int().positive(), targetType: z.enum(["catalog", "category", "product"]).default("catalog"), targetValue: z.string().trim().max(191).default(""), startAt: z.string().datetime().nullable().default(null), endAt: z.string().datetime().nullable().default(null), status: z.enum(["draft", "scheduled", "active", "ended"]).default("draft") }).superRefine((value, ctx) => { if (value.discountType === "percentage" && value.discountValue > 100) ctx.addIssue({ code: z.ZodIssueCode.custom, path: ["discountValue"], message: "Percentage discounts cannot exceed 100." }); if (value.startAt && value.endAt && new Date(value.endAt) <= new Date(value.startAt)) ctx.addIssue({ code: z.ZodIssueCode.custom, path: ["endAt"], message: "End time must be after start time." }); });
const bannerSchema = z.object({ imageUrl: z.string().url(), title: z.string().trim().min(2).max(255), subtitle: z.string().trim().max(500).default(""), ctaText: z.string().trim().max(128).default(""), destination: z.string().trim().regex(/^(\/|https:\/\/)/).max(500), startAt: z.string().datetime().nullable().default(null), endAt: z.string().datetime().nullable().default(null), status: z.enum(["draft", "scheduled", "active", "ended"]).default("draft"), sortOrder: z.coerce.number().int().min(0).max(10000).default(0) });
const inventorySchema = z.object({ productKey: z.string().min(1).max(191), adjustment: z.coerce.number().int().min(-1_000_000).max(1_000_000).refine((value) => value !== 0, "Adjustment cannot be zero."), reason: z.string().trim().min(3).max(500) });
const orderSchema = z.object({ fulfillmentStatus: z.enum(["pending", "processing", "packed", "shipped", "delivered", "cancelled"]) });
const roleSchema = z.object({ role: z.enum(roles) });

function id(prefix: string) { return `${prefix}-${crypto.randomUUID().slice(0, 8)}`; }
function availability(stock: number): AdminProduct["availability"] { return stock <= 0 ? "out-of-stock" : stock < 5 ? "low-stock" : "in-stock"; }
function rowProduct(row: typeof catalogProducts.$inferSelect): AdminProduct {
  const payload = (row.payload ?? {}) as Record<string, unknown>;
  return { id: row.productKey, slug: row.slug, name: row.name, pricePkr: row.pricePkr, stock: row.stock, status: row.status, category: String(payload.category ?? "Uncategorised"), collection: String(payload.collection ?? "Essentials"), description: String(payload.description ?? ""), images: Array.isArray(payload.images) ? payload.images.filter((value): value is string => typeof value === "string") : [], tags: Array.isArray(payload.tags) ? payload.tags.filter((value): value is string => typeof value === "string") : [], featured: payload.featured === true, availability: availability(row.stock) };
}
function dbProductValues(product: AdminProduct) { return { productKey: product.id, slug: product.slug, name: product.name, pricePkr: product.pricePkr, stock: product.stock, status: product.status, payload: { category: product.category, collection: product.collection, description: product.description, images: product.images, tags: product.tags, featured: product.featured } }; }
async function productsSnapshot(): Promise<AdminProduct[]> { const db = await getDb(); if (!db) return state.products; const rows = await db.select().from(catalogProducts).orderBy(desc(catalogProducts.updatedAt)); return rows.length ? rows.map(rowProduct) : state.products; }
async function categoriesSnapshot(): Promise<AdminCategory[]> { const db = await getDb(); if (!db) return state.categories; const rows = await db.select().from(adminCategories).orderBy(adminCategories.sortOrder); return rows.length ? rows.map((row) => ({ id: String(row.id), slug: row.slug, name: row.name, description: row.description ?? "", imageUrl: row.imageUrl ?? "", status: row.status, sortOrder: row.sortOrder })) : state.categories; }
async function promotionsSnapshot(): Promise<AdminPromotion[]> { const db = await getDb(); if (!db) return state.promotions; const rows = await db.select().from(adminPromotions).orderBy(desc(adminPromotions.updatedAt)); return rows.map((row) => ({ id: String(row.id), name: row.name, description: row.description ?? "", discountType: row.discountType as AdminPromotion["discountType"], discountValue: row.discountValue, targetType: row.targetType as AdminPromotion["targetType"], targetValue: row.targetValue ?? "", startAt: row.startAt?.toISOString() ?? null, endAt: row.endAt?.toISOString() ?? null, status: row.status as AdminPromotion["status"] })); }
async function bannersSnapshot(): Promise<AdminBanner[]> { const db = await getDb(); if (!db) return state.banners; const rows = await db.select().from(adminBanners).orderBy(adminBanners.sortOrder); return rows.map((row) => ({ id: String(row.id), imageUrl: row.imageUrl, title: row.title, subtitle: row.subtitle ?? "", ctaText: row.ctaText ?? "", destination: row.destination, startAt: row.startAt?.toISOString() ?? null, endAt: row.endAt?.toISOString() ?? null, status: row.status as AdminBanner["status"], sortOrder: row.sortOrder })); }
function parseBody<T>(schema: z.ZodType<T>, body: unknown): T { const parsed = schema.safeParse(body); if (!parsed.success) throw Object.assign(new Error(parsed.error.issues.map((issue) => `${issue.path.join(".") || "value"}: ${issue.message}`).join("; ")), { status: 400 }); return parsed.data; }

async function audit(req: Request, actor: SessionUser, action: string, resource: string, resourceId: string | null, changedFields: Record<string, unknown>) {
  const actorRole = await resolveRole(req, actor);
  const event: AdminAudit = { id: id("audit"), actorUserId: actor.id, actorRole, action, resource, resourceId, changedFields, requestId: req.res?.locals.requestId ?? null, createdAt: new Date().toISOString() };
  const db = await getDb();
  if (db) await db.insert(adminAuditEvents).values({ actorUserId: event.actorUserId, actorRole: event.actorRole, action, resource, resourceId, changedFields, requestId: event.requestId });
  else state.audit.unshift(event);
}

async function resolveRole(req: Request, actor: SessionUser): Promise<AdminRole> {
  if (actor.owner || actor.id === "demo-owner") return "owner";
  const sessionRole = actor.role as AdminRole | undefined;
  const db = await getDb();
  if (db) {
    const rows = await db.select({ role: users.role }).from(users).where(eq(users.openId, actor.id)).limit(1);
    const role = rows[0]?.role as AdminRole | undefined;
    if (role && roles.includes(role)) return role;
  }
  return sessionRole && roles.includes(sessionRole) ? sessionRole : "staff";
}
async function can(req: Request, permission: string) { const actor = currentUser(req); if (!actor) return null; const role = await resolveRole(req, actor); return hasAdminPermission(role, permission) ? { actor, role } : null; }
function guard(permission: string) {
  return (req: Request, res: Response, next: (error?: unknown) => void) => {
    requireSession(req, res, async (error?: unknown) => {
      if (error) return next(error);
      try {
        const access = await can(req, permission);
        if (!access) return res.status(403).json({ error: { code: "FORBIDDEN", message: "You do not have permission to perform this operation.", requestId: res.locals.requestId } });
        res.locals.admin = access;
        next();
      } catch (caught) {
        next(caught);
      }
    });
  };
}
function actor(req: Request) { return currentUser(req) as SessionUser; }
function adminRole(req: Request) { return (resLocals(req).admin as { role: AdminRole }).role; }
function resLocals(req: Request) { return req.res?.locals as Record<string, unknown>; }

export async function getStorefrontCatalog() {
  const [products, categories, promotions, banners] = await Promise.all([productsSnapshot(), categoriesSnapshot(), promotionsSnapshot(), bannersSnapshot()]);
  const activeProducts = products.filter((product) => product.status === "active").sort((a, b) => a.id.localeCompare(b.id));
  const activeBanners = banners.filter((banner) => banner.status === "active").sort((a, b) => a.sortOrder - b.sortOrder);
  return { products: activeProducts.length ? activeProducts : seedProducts, collections: seedCollections, journals: [], categories, promotions, banners: activeBanners };
}

export function registerAdminRoutes(app: Express) {
  app.post("/api/admin/demo-login", async (_req, res, next) => { try { const allowed = (appEnvironment === "development" || appEnvironment === "test") && process.env.ALLOW_DEMO_LOGIN !== "false"; if (!allowed) return res.status(404).end(); await setSession(res, { id: "demo-owner", name: "Demo Owner", email: "owner@local.demo", owner: true, role: "owner" }); return res.json({ ok: true, demo: true }); } catch (error) { next(error); } });
  app.get("/api/admin/bootstrap", guard("dashboard"), async (req, res, next) => { try { const [products, categories, promotions, banners] = await Promise.all([productsSnapshot(), categoriesSnapshot(), promotionsSnapshot(), bannersSnapshot()]); const role = adminRole(req); const orderRows = (await getDb()) ? await (await getDb())!.select().from(orders).orderBy(desc(orders.createdAt)).limit(10) : []; return res.json({ actor: { ...actor(req), role }, navigation: Object.entries(rolePermissions[role]).filter(([, allowed]) => allowed).map(([key]) => key), metrics: { totalProducts: products.length, activeProducts: products.filter((item) => item.status === "active").length, lowStock: products.filter((item) => item.stock > 0 && item.stock < 5).length, outOfStock: products.filter((item) => item.stock <= 0).length, activePromotions: promotions.filter((item) => item.status === "active").length, pendingOrders: orderRows.filter((item) => item.fulfillmentStatus === "pending").length }, recentOrders: orderRows, recentAudit: state.audit.slice(0, 8), counts: { products: products.length, categories: categories.length, promotions: promotions.length, banners: banners.length } }); } catch (error) { next(error); } });

  app.get("/api/admin/products", guard("products"), async (req, res, next) => { try { const query = String(req.query.q ?? "").trim().toLowerCase(); const status = String(req.query.status ?? ""); const items = (await productsSnapshot()).filter((item) => (!query || `${item.name} ${item.slug} ${item.category}`.toLowerCase().includes(query)) && (!status || item.status === status)); res.json({ items }); } catch (error) { next(error); } });
  app.post("/api/admin/products", guard("products"), async (req, res, next) => { try { const input = parseBody(productSchema, req.body); const product: AdminProduct = { ...input, id: id("p"), availability: availability(input.stock) }; const db = await getDb(); if (db) await db.insert(catalogProducts).values(dbProductValues(product)); else state.products.unshift(product); await audit(req, actor(req), "product.created", "product", product.id, { name: product.name, pricePkr: product.pricePkr, stock: product.stock }); res.status(201).json({ item: product }); } catch (error) { next(error); } });
  app.patch("/api/admin/products/:id", guard("products"), async (req, res, next) => { try { const current = (await productsSnapshot()).find((item) => item.id === String(req.params.id)); if (!current) return res.status(404).json({ error: { code: "NOT_FOUND", message: "Product was not found." } }); const input = parseBody(productSchema.partial(), { ...current, ...req.body }); const product = { ...current, ...input, availability: availability(input.stock ?? current.stock) }; const db = await getDb(); if (db) await db.update(catalogProducts).set(dbProductValues(product)).where(eq(catalogProducts.productKey, product.id)); else state.products = state.products.map((item) => item.id === product.id ? product : item); await audit(req, actor(req), "product.updated", "product", product.id, req.body ?? {}); res.json({ item: product }); } catch (error) { next(error); } });
  app.delete("/api/admin/products/:id", guard("products"), async (req, res, next) => { try { const db = await getDb(); if (db) await db.update(catalogProducts).set({ status: "archived" }).where(eq(catalogProducts.productKey, String(req.params.id))); else state.products = state.products.map((item) => item.id === String(req.params.id) ? { ...item, status: "archived" } : item); await audit(req, actor(req), "product.archived", "product", String(req.params.id), { status: "archived" }); res.status(204).end(); } catch (error) { next(error); } });

  app.get("/api/admin/categories", guard("categories"), async (_req, res, next) => { try { res.json({ items: await categoriesSnapshot() }); } catch (error) { next(error); } });
  app.post("/api/admin/categories", guard("categories"), async (req, res, next) => { try { const input = parseBody(categorySchema, req.body); const category: AdminCategory = { ...input, id: id("cat") }; const db = await getDb(); if (db) { const [inserted] = await db.insert(adminCategories).values(input).returning({ id: adminCategories.id }); category.id = String(inserted?.id ?? category.id); } else state.categories.push(category); await audit(req, actor(req), "category.created", "category", category.id, input); res.status(201).json({ item: category }); } catch (error) { next(error); } });
  app.patch("/api/admin/categories/:id", guard("categories"), async (req, res, next) => { try { const input = parseBody(categorySchema.partial(), req.body); const existing = (await categoriesSnapshot()).find((item) => item.id === String(req.params.id)); if (!existing) return res.status(404).json({ error: { code: "NOT_FOUND", message: "Category was not found." } }); const item = { ...existing, ...input }; const db = await getDb(); if (db) await db.update(adminCategories).set(input).where(eq(adminCategories.id, Number(String(req.params.id)))); else state.categories = state.categories.map((row) => row.id === item.id ? item : row); await audit(req, actor(req), "category.updated", "category", item.id, input); res.json({ item }); } catch (error) { next(error); } });
  app.delete("/api/admin/categories/:id", guard("categories"), async (req, res, next) => { try { const existing = (await categoriesSnapshot()).find((item) => item.id === String(req.params.id)); if (!existing) return res.status(404).json({ error: { code: "NOT_FOUND", message: "Category was not found." } }); const inUse = (await productsSnapshot()).some((product) => product.category.toLowerCase() === existing.name.toLowerCase() && product.status !== "archived"); if (inUse) return res.status(409).json({ error: { code: "CATEGORY_IN_USE", message: "Reassign products before archiving this category." } }); const db = await getDb(); if (db) await db.update(adminCategories).set({ status: "archived" }).where(eq(adminCategories.id, Number(String(req.params.id)))); else state.categories = state.categories.map((row) => row.id === String(req.params.id) ? { ...row, status: "archived" } : row); await audit(req, actor(req), "category.archived", "category", String(req.params.id), { status: "archived" }); res.status(204).end(); } catch (error) { next(error); } });

  app.get("/api/admin/inventory", guard("inventory"), async (_req, res, next) => { try { const products = await productsSnapshot(); res.json({ items: products.map((item) => ({ ...item, availableStock: item.stock })) }); } catch (error) { next(error); } });
  app.post("/api/admin/inventory/adjust", guard("inventory"), async (req, res, next) => { try { const input = parseBody(inventorySchema, req.body); const products = await productsSnapshot(); const product = products.find((item) => item.id === input.productKey); if (!product) return res.status(404).json({ error: { code: "NOT_FOUND", message: "Product was not found." } }); const nextStock = product.stock + input.adjustment; if (nextStock < 0) return res.status(409).json({ error: { code: "NEGATIVE_STOCK", message: "Inventory cannot become negative." } }); const db = await getDb(); if (db) { const updated = await db.update(catalogProducts).set({ stock: sql`${catalogProducts.stock} + ${input.adjustment}` }).where(and(eq(catalogProducts.productKey, product.id), sql`${catalogProducts.stock} + ${input.adjustment} >= 0`)).returning({ productKey: catalogProducts.productKey }); if (updated.length !== 1) return res.status(409).json({ error: { code: "STOCK_CONFLICT", message: "Inventory changed before this adjustment could be applied." } }); await db.insert(inventoryAdjustments).values({ productKey: product.id, previousQuantity: product.stock, adjustment: input.adjustment, resultingQuantity: nextStock, reason: input.reason, actorUserId: actor(req).id, requestId: req.res?.locals.requestId }); } else { state.products = state.products.map((item) => item.id === product.id ? { ...item, stock: nextStock, availability: availability(nextStock) } : item); state.adjustments.unshift({ id: id("adjust"), ...input, previousQuantity: product.stock, resultingQuantity: nextStock, actorUserId: actor(req).id, createdAt: new Date().toISOString() }); } await audit(req, actor(req), "inventory.adjusted", "product", product.id, { previousQuantity: product.stock, adjustment: input.adjustment, resultingQuantity: nextStock, reason: input.reason }); res.json({ item: { ...product, stock: nextStock, availability: availability(nextStock) } }); } catch (error) { next(error); } });

  app.get("/api/admin/promotions", guard("promotions"), async (_req, res, next) => { try { res.json({ items: await promotionsSnapshot() }); } catch (error) { next(error); } });
  app.post("/api/admin/promotions", guard("promotions"), async (req, res, next) => { try { const input = parseBody(promotionSchema, req.body); const item: AdminPromotion = { ...input, id: id("promo") }; if (item.discountType === "percentage" && item.discountValue > 100) return badRequest(res, "Percentage discounts cannot exceed 100."); const db = await getDb(); if (db) { const [inserted] = await db.insert(adminPromotions).values({ ...input, startAt: input.startAt ? new Date(input.startAt) : null, endAt: input.endAt ? new Date(input.endAt) : null }).returning({ id: adminPromotions.id }); item.id = String(inserted?.id ?? item.id); } else state.promotions.unshift(item); await audit(req, actor(req), "promotion.created", "promotion", item.id, input); res.status(201).json({ item }); } catch (error) { next(error); } });
  app.patch("/api/admin/promotions/:id", guard("promotions"), async (req, res, next) => { try { const current = (await promotionsSnapshot()).find((item) => item.id === String(req.params.id)); if (!current) return res.status(404).json({ error: { code: "NOT_FOUND", message: "Promotion was not found." } }); const input = parseBody(promotionSchema.partial(), { ...current, ...req.body }); const item = { ...current, ...input }; const db = await getDb(); if (db) await db.update(adminPromotions).set({ ...input, startAt: input.startAt ? new Date(input.startAt) : null, endAt: input.endAt ? new Date(input.endAt) : null }).where(eq(adminPromotions.id, Number(String(req.params.id)))); else state.promotions = state.promotions.map((row) => row.id === item.id ? item : row); await audit(req, actor(req), `promotion.${input.status === "active" ? "activated" : "updated"}`, "promotion", item.id, input); res.json({ item }); } catch (error) { next(error); } });

  app.get("/api/admin/banners", guard("banners"), async (_req, res, next) => { try { res.json({ items: await bannersSnapshot() }); } catch (error) { next(error); } });
  app.post("/api/admin/banners", guard("banners"), async (req, res, next) => { try { const input = parseBody(bannerSchema, req.body); const item: AdminBanner = { ...input, id: id("banner") }; const db = await getDb(); if (db) { const [inserted] = await db.insert(adminBanners).values({ ...input, startAt: input.startAt ? new Date(input.startAt) : null, endAt: input.endAt ? new Date(input.endAt) : null }).returning({ id: adminBanners.id }); item.id = String(inserted?.id ?? item.id); } else state.banners.push(item); await audit(req, actor(req), "banner.created", "banner", item.id, input); res.status(201).json({ item }); } catch (error) { next(error); } });
  app.patch("/api/admin/banners/:id", guard("banners"), async (req, res, next) => { try { const current = (await bannersSnapshot()).find((item) => item.id === String(req.params.id)); if (!current) return res.status(404).json({ error: { code: "NOT_FOUND", message: "Banner was not found." } }); const input = parseBody(bannerSchema.partial(), { ...current, ...req.body }); const item = { ...current, ...input }; const db = await getDb(); if (db) await db.update(adminBanners).set({ ...input, startAt: input.startAt ? new Date(input.startAt) : null, endAt: input.endAt ? new Date(input.endAt) : null }).where(eq(adminBanners.id, Number(String(req.params.id)))); else state.banners = state.banners.map((row) => row.id === item.id ? item : row); await audit(req, actor(req), `banner.${input.status === "active" ? "published" : "updated"}`, "banner", item.id, input); res.json({ item }); } catch (error) { next(error); } });

  app.get("/api/admin/orders", guard("orders"), async (_req, res, next) => { try { const db = await getDb(); const items = db ? await db.select().from(orders).orderBy(desc(orders.createdAt)).limit(200) : []; res.json({ items }); } catch (error) { next(error); } });
  app.patch("/api/admin/orders/:id", guard("orders"), async (req, res, next) => { try { const input = parseBody(orderSchema, req.body); const db = await getDb(); if (!db) return res.status(404).json({ error: { code: "NO_DATABASE", message: "Order operations require the configured commerce database." } }); const existing = await db.select().from(orders).where(eq(orders.orderNumber, String(req.params.id))).limit(1); if (!existing[0]) return res.status(404).json({ error: { code: "NOT_FOUND", message: "Order was not found." } }); await db.update(orders).set({ fulfillmentStatus: input.fulfillmentStatus }).where(eq(orders.orderNumber, String(req.params.id))); await audit(req, actor(req), "order.fulfillment_updated", "order", String(req.params.id), input); res.json({ ok: true }); } catch (error) { next(error); } });

  app.get("/api/admin/customers", guard("customers"), async (_req, res, next) => { try { const db = await getDb(); const items = db ? await db.select({ id: users.id, openId: users.openId, email: users.email, name: users.name, role: users.role, createdAt: users.createdAt }).from(users).orderBy(desc(users.createdAt)).limit(200) : []; res.json({ items }); } catch (error) { next(error); } });
  app.get("/api/admin/staff", guard("staff"), async (_req, res, next) => { try { const db = await getDb(); const items = db ? await db.select({ id: users.id, openId: users.openId, email: users.email, name: users.name, role: users.role, createdAt: users.createdAt }).from(users).where(sql`${users.role} in ('owner','admin','staff')`).orderBy(desc(users.createdAt)).limit(200) : [{ id: "demo-owner", openId: "demo-owner", email: "owner@local.demo", name: "Demo Owner", role: "owner", createdAt: new Date() }]; res.json({ items }); } catch (error) { next(error); } });
  app.patch("/api/admin/staff/:id", guard("staff"), async (req, res, next) => { try { const input = parseBody(roleSchema, req.body); const db = await getDb(); if (!db) return res.status(404).json({ error: { code: "NO_DATABASE", message: "Staff management requires the configured commerce database." } }); if (String((await db.select({ role: users.role }).from(users).where(eq(users.id, Number(String(req.params.id)))).limit(1))[0]?.role) === "owner") return res.status(409).json({ error: { code: "OWNER_PROTECTED", message: "The owner role cannot be reassigned from this panel." } }); await db.update(users).set({ role: input.role }).where(eq(users.id, Number(String(req.params.id)))); await audit(req, actor(req), "staff.role_updated", "staff", String(req.params.id), input); res.json({ ok: true }); } catch (error) { next(error); } });
  app.get("/api/admin/audit", guard("audit"), async (_req, res, next) => { try { const db = await getDb(); const items = db ? await db.select().from(adminAuditEvents).orderBy(desc(adminAuditEvents.createdAt)).limit(200) : state.audit; res.json({ items }); } catch (error) { next(error); } });
  app.get("/api/admin/settings", guard("settings"), async (_req, res, next) => { try { const db = await getDb(); res.json({ items: [{ key: "workspace", value: "Usamabhanbhro Merchant Studio" }, { key: "environment", value: process.env.APP_ENV ?? "development" }, { key: "persistence", value: db ? "database-backed" : "in-memory demo store" }, { key: "catalog", value: "server-owned catalog snapshot" }, { key: "payments", value: "demo-only; no real transactions" }] }); } catch (error) { next(error); } });
  app.post("/api/admin/media/presign", guard("products"), async (req, res, next) => { try { const key = String(req.body?.key ?? ""); const contentType = String(req.body?.contentType ?? ""); const size = Number(req.body?.size ?? 0); res.status(201).json(await createUploadUrl({ key, contentType, size })); } catch (error) { next(error); } });
}
