import { and, desc, eq, sql } from "drizzle-orm";
import { z } from "zod";
import { adminAuditEvents, adminBanners, adminCategories, adminPromotions, catalogProducts, inventoryAdjustments, orders, users } from "../drizzle/schema";
import { collections as seedCollections, products as seedProducts } from "../client/src/lib/catalog";
import { effectivePromotionStatus, selectBestPromotion, type PromotionRecord } from "../shared/promotions";
import { getDb } from "./db";
import { appEnvironment } from "./env";
import { currentUser, requireSession, setSession, type SessionUser } from "./auth";
import { createUploadUrl, deleteObject } from "./storage";
import type { Express, Request, Response } from "express";

export const roles = ["owner", "admin", "staff"] as const;
export type AdminRole = (typeof roles)[number];
export const rolePermissions: Record<AdminRole, Record<string, boolean>> = {
  owner: { dashboard: true, products: true, categories: true, inventory: true, promotions: true, banners: true, orders: true, customers: true, staff: true, audit: true, settings: true },
  admin: { dashboard: true, products: true, categories: true, inventory: true, promotions: true, banners: true, orders: true, customers: true, staff: false, audit: true, settings: true },
  staff: { dashboard: true, products: true, categories: false, inventory: true, promotions: false, banners: false, orders: true, customers: true, staff: false, audit: true, settings: false },
};
export function hasAdminPermission(role: AdminRole, permission: string) { return rolePermissions[role]?.[permission] === true; }

export type AdminProduct = { id: string; slug: string; name: string; pricePkr: number; stock: number; status: string; category: string; collection: string; description: string; images: string[]; tags: string[]; featured: boolean; availability: "in-stock" | "low-stock" | "out-of-stock" };
export type AdminCategory = { id: string; slug: string; name: string; description: string; imageUrl: string; status: string; sortOrder: number };
export type AdminPromotion = PromotionRecord & { description: string };
export type AdminBanner = { id: string; imageUrl: string; title: string; subtitle: string; ctaText: string; destination: string; startAt: string | null; endAt: string | null; status: "draft" | "scheduled" | "active" | "ended"; sortOrder: number };
export type AdminAudit = { id: string; actorUserId: string; actorRole: AdminRole; action: string; resource: string; resourceId: string | null; changedFields: Record<string, unknown>; requestId: string | null; createdAt: string };

type AdminState = { products: AdminProduct[]; categories: AdminCategory[]; promotions: AdminPromotion[]; banners: AdminBanner[]; adjustments: Array<Record<string, unknown>>; audit: AdminAudit[] };
const state: AdminState = {
  products: seedProducts.map((product) => ({ id: product.id, slug: product.slug, name: product.name, pricePkr: product.price, stock: product.availability === "low-stock" ? 4 : 20, status: "active", category: product.category, collection: product.collection, description: product.description, images: product.images, tags: product.tags, featured: product.tags.includes("best-seller"), availability: product.availability })),
  categories: Array.from(new Map(seedProducts.map((product) => [product.category, product.category])).keys()).map((name, index) => ({ id: `cat-${index + 1}`, slug: name.toLowerCase().replace(/[^a-z0-9]+/g, "-"), name, description: `The ${name.toLowerCase()} edit.`, imageUrl: seedCollections.find((item) => item.name.toLowerCase() === name.toLowerCase())?.image ?? seedCollections[0]?.image ?? "", status: "active", sortOrder: index })),
  promotions: [], banners: [], adjustments: [], audit: [],
};

const mediaUrl = z.string().url().or(z.string().regex(/^\/storage\/[a-zA-Z0-9/_-]+$/));
const productSchema = z.object({ name: z.string().trim().min(2).max(255), slug: z.string().trim().regex(/^[a-z0-9]+(?:-[a-z0-9]+)*$/).max(191), pricePkr: z.coerce.number().int().nonnegative().max(10_000_000), stock: z.coerce.number().int().nonnegative().max(1_000_000), category: z.string().trim().min(1).max(128), collection: z.string().trim().min(1).max(128), description: z.string().trim().min(10).max(2000), images: z.array(mediaUrl).max(8).default([]), tags: z.array(z.string().trim().min(1).max(64)).max(20).default([]), featured: z.boolean().default(false), status: z.enum(["active", "draft", "archived"]).default("active") });
const categorySchema = z.object({ slug: z.string().trim().regex(/^[a-z0-9]+(?:-[a-z0-9]+)*$/).max(191), name: z.string().trim().min(2).max(255), description: z.string().trim().max(1000).default(""), imageUrl: mediaUrl.or(z.literal("")).default(""), status: z.enum(["active", "draft", "archived"]).default("active"), sortOrder: z.coerce.number().int().min(0).max(10000).default(0) });
const promotionSchema = z.object({ name: z.string().trim().min(2).max(255), description: z.string().trim().max(1000).default(""), discountType: z.enum(["percentage", "fixed"]), discountValue: z.coerce.number().int().positive().max(10_000_000), targetType: z.enum(["catalog", "category", "product"]).default("catalog"), targetValue: z.string().trim().max(191).default(""), startAt: z.string().datetime().nullable().default(null), endAt: z.string().datetime().nullable().default(null), status: z.enum(["draft", "scheduled", "active", "ended"]).default("draft") }).superRefine((value, ctx) => { if (value.discountType === "percentage" && value.discountValue > 100) ctx.addIssue({ code: z.ZodIssueCode.custom, path: ["discountValue"], message: "Percentage discounts cannot exceed 100." }); if (value.targetType !== "catalog" && !value.targetValue) ctx.addIssue({ code: z.ZodIssueCode.custom, path: ["targetValue"], message: "A category or product target is required." }); if (value.targetType === "catalog" && value.targetValue) ctx.addIssue({ code: z.ZodIssueCode.custom, path: ["targetValue"], message: "Catalog promotions do not use a target value." }); if (value.startAt && value.endAt && new Date(value.endAt) <= new Date(value.startAt)) ctx.addIssue({ code: z.ZodIssueCode.custom, path: ["endAt"], message: "End time must be after start time." }); });
const campaignPatchSchema = promotionSchema.partial();
const bannerSchema = z.object({ imageUrl: mediaUrl, title: z.string().trim().min(2).max(255), subtitle: z.string().trim().max(500).default(""), ctaText: z.string().trim().max(128).default(""), destination: z.string().trim().regex(/^(\/|https:\/\/)/).max(500), startAt: z.string().datetime().nullable().default(null), endAt: z.string().datetime().nullable().default(null), status: z.enum(["draft", "scheduled", "active", "ended"]).default("draft"), sortOrder: z.coerce.number().int().min(0).max(10000).default(0) }).superRefine((value, ctx) => { if (value.startAt && value.endAt && new Date(value.endAt) <= new Date(value.startAt)) ctx.addIssue({ code: z.ZodIssueCode.custom, path: ["endAt"], message: "End time must be after start time." }); });
const inventorySchema = z.object({ productKey: z.string().min(1).max(191), adjustment: z.coerce.number().int().min(-1_000_000).max(1_000_000).refine((value) => value !== 0, "Adjustment cannot be zero."), reason: z.string().trim().min(3).max(500) });
const orderSchema = z.object({ fulfillmentStatus: z.enum(["pending", "processing", "packed", "shipped", "delivered", "cancelled"]) });
const roleSchema = z.object({ role: z.enum(roles) });

function id(prefix: string) { return `${prefix}-${crypto.randomUUID().slice(0, 8)}`; }
function availability(stock: number): AdminProduct["availability"] { return stock <= 0 ? "out-of-stock" : stock < 5 ? "low-stock" : "in-stock"; }
function rowProduct(row: typeof catalogProducts.$inferSelect): AdminProduct { const payload = (row.payload ?? {}) as Record<string, unknown>; return { id: row.productKey, slug: row.slug, name: row.name, pricePkr: row.pricePkr, stock: row.stock, status: row.status, category: String(payload.category ?? "Uncategorised"), collection: String(payload.collection ?? "Essentials"), description: String(payload.description ?? ""), images: Array.isArray(payload.images) ? payload.images.filter((value): value is string => typeof value === "string") : [], tags: Array.isArray(payload.tags) ? payload.tags.filter((value): value is string => typeof value === "string") : [], featured: payload.featured === true, availability: availability(row.stock) }; }
function dbProductValues(product: AdminProduct) { return { productKey: product.id, slug: product.slug, name: product.name, pricePkr: product.pricePkr, stock: product.stock, status: product.status, payload: { category: product.category, collection: product.collection, description: product.description, images: product.images, tags: product.tags, featured: product.featured } }; }
function parseBody<T>(schema: z.ZodType<T>, body: unknown): T { const parsed = schema.safeParse(body); if (!parsed.success) throw Object.assign(new Error(parsed.error.issues.map((issue) => `${issue.path.join(".") || "value"}: ${issue.message}`).join("; ")), { status: 400 }); return parsed.data; }
function campaignStatus(input: { status: AdminPromotion["status"]; startAt: string | null; endAt: string | null }) { return effectivePromotionStatus(input); }

async function productsSnapshot(): Promise<AdminProduct[]> { const db = await getDb(); if (!db) return state.products; const rows = await db.select().from(catalogProducts).orderBy(desc(catalogProducts.updatedAt)); return rows.length ? rows.map(rowProduct) : state.products; }
async function categoriesSnapshot(): Promise<AdminCategory[]> { const db = await getDb(); if (!db) return state.categories; const rows = await db.select().from(adminCategories).orderBy(adminCategories.sortOrder); return rows.length ? rows.map((row) => ({ id: String(row.id), slug: row.slug, name: row.name, description: row.description ?? "", imageUrl: row.imageUrl ?? "", status: row.status, sortOrder: row.sortOrder })) : state.categories; }
async function promotionsSnapshot(): Promise<AdminPromotion[]> { const db = await getDb(); if (!db) return state.promotions; const rows = await db.select().from(adminPromotions).orderBy(desc(adminPromotions.updatedAt)); return rows.map((row) => ({ id: String(row.id), name: row.name, description: row.description ?? "", discountType: row.discountType as AdminPromotion["discountType"], discountValue: row.discountValue, targetType: row.targetType as AdminPromotion["targetType"], targetValue: row.targetValue ?? "", startAt: row.startAt?.toISOString() ?? null, endAt: row.endAt?.toISOString() ?? null, status: campaignStatus({ status: row.status as AdminPromotion["status"], startAt: row.startAt?.toISOString() ?? null, endAt: row.endAt?.toISOString() ?? null }) })); }
async function bannersSnapshot(): Promise<AdminBanner[]> { const db = await getDb(); if (!db) return state.banners; const rows = await db.select().from(adminBanners).orderBy(adminBanners.sortOrder); return rows.map((row) => ({ id: String(row.id), imageUrl: row.imageUrl, title: row.title, subtitle: row.subtitle ?? "", ctaText: row.ctaText ?? "", destination: row.destination, startAt: row.startAt?.toISOString() ?? null, endAt: row.endAt?.toISOString() ?? null, status: campaignStatus({ status: row.status as AdminPromotion["status"], startAt: row.startAt?.toISOString() ?? null, endAt: row.endAt?.toISOString() ?? null }), sortOrder: row.sortOrder })); }

async function resolveRole(req: Request, actor: SessionUser): Promise<AdminRole> { if (actor.owner || actor.id === "demo-owner") return "owner"; const db = await getDb(); if (db) { const rows = await db.select({ role: users.role }).from(users).where(eq(users.openId, actor.id)).limit(1); const role = rows[0]?.role as AdminRole | undefined; if (role && roles.includes(role)) return role; } return actor.role && roles.includes(actor.role as AdminRole) ? actor.role as AdminRole : "staff"; }
async function can(req: Request, permission: string) { const actor = currentUser(req); if (!actor) return null; const role = await resolveRole(req, actor); return hasAdminPermission(role, permission) ? { actor, role } : null; }
function guard(permission: string) { return (req: Request, res: Response, next: (error?: unknown) => void) => { requireSession(req, res, async (error?: unknown) => { if (error) return next(error); try { const access = await can(req, permission); if (!access) return res.status(403).json({ error: { code: "FORBIDDEN", message: "You do not have permission to perform this operation.", requestId: res.locals.requestId } }); res.locals.admin = access; next(); } catch (caught) { next(caught); } }); }; }
function mediaGuard(req: Request, res: Response, next: (error?: unknown) => void) { requireSession(req, res, async (error?: unknown) => { if (error) return next(error); const productAccess = await can(req, "products"); const categoryAccess = await can(req, "categories"); const bannerAccess = await can(req, "banners"); if (!productAccess && !categoryAccess && !bannerAccess) return res.status(403).json({ error: { code: "FORBIDDEN", message: "You do not have permission to manage merchant media.", requestId: res.locals.requestId } }); res.locals.admin = productAccess ?? categoryAccess ?? bannerAccess; next(); }); }
function actor(req: Request) { return currentUser(req) as SessionUser; }
function adminRole(req: Request) { return (req.res?.locals.admin as { role: AdminRole }).role; }

async function audit(req: Request, actorUser: SessionUser, action: string, resource: string, resourceId: string | null, changedFields: Record<string, unknown>) { const event: AdminAudit = { id: id("audit"), actorUserId: actorUser.id, actorRole: adminRole(req), action, resource, resourceId, changedFields, requestId: req.res?.locals.requestId ?? null, createdAt: new Date().toISOString() }; const db = await getDb(); if (db) await db.insert(adminAuditEvents).values({ actorUserId: event.actorUserId, actorRole: event.actorRole, action, resource, resourceId, changedFields, requestId: event.requestId }); else state.audit.unshift(event); }
async function validateCategoryReference(category: string) { const categories = (await categoriesSnapshot()).filter((item) => item.status !== "archived"); if (!categories.some((item) => item.slug === category || item.name.toLowerCase() === category.toLowerCase())) throw Object.assign(new Error("category: Select an existing active category."), { status: 400 }); }
async function validatePromotionTarget(input: Pick<AdminPromotion, "targetType" | "targetValue">) { if (input.targetType === "catalog") return; if (input.targetType === "category") { const categories = await categoriesSnapshot(); if (!categories.some((item) => item.status !== "archived" && (item.slug === input.targetValue || item.name.toLowerCase() === input.targetValue.toLowerCase()))) throw Object.assign(new Error("targetValue: Select an existing active category."), { status: 400 }); return; } const products = await productsSnapshot(); if (!products.some((item) => item.status !== "archived" && (item.id === input.targetValue || item.slug === input.targetValue))) throw Object.assign(new Error("targetValue: Select an existing active product."), { status: 400 }); }

export async function getStorefrontCatalog() {
  const [products, categories, promotions, banners] = await Promise.all([productsSnapshot(), categoriesSnapshot(), promotionsSnapshot(), bannersSnapshot()]);
  const livePromotions = promotions.filter((item) => item.status === "active");
  const activeProducts = products.filter((product) => product.status === "active").sort((a, b) => a.id.localeCompare(b.id)).map((product) => { const promotion = selectBestPromotion(product.pricePkr, product, livePromotions); return { ...product, pricePkr: promotion?.pricePkr ?? product.pricePkr, compareAtPricePkr: promotion?.compareAtPricePkr, promotion: promotion ? { id: promotion.id, name: promotion.name, discountPkr: promotion.discountPkr } : null }; });
  const activeBanners = banners.filter((banner) => banner.status === "active").sort((a, b) => a.sortOrder - b.sortOrder);
  return { products: activeProducts.length ? activeProducts : seedProducts, collections: seedCollections, journals: [], categories: categories.filter((item) => item.status === "active"), promotions: livePromotions, banners: activeBanners };
}

export function registerAdminRoutes(app: Express) {
  app.post("/api/admin/demo-login", async (_req, res, next) => { try { const allowed = (appEnvironment === "development" || appEnvironment === "test") && process.env.ALLOW_DEMO_LOGIN !== "false"; if (!allowed) return res.status(404).end(); await setSession(res, { id: "demo-owner", name: "Demo Owner", email: "owner@local.demo", owner: true, role: "owner" }); return res.json({ ok: true, demo: true }); } catch (error) { next(error); } });
  app.get("/api/admin/bootstrap", guard("dashboard"), async (req, res, next) => { try { const [products, categories, promotions, banners, db] = await Promise.all([productsSnapshot(), categoriesSnapshot(), promotionsSnapshot(), bannersSnapshot(), getDb()]); const role = adminRole(req); const orderRows = db ? await db.select().from(orders).orderBy(desc(orders.createdAt)).limit(10) : []; const auditRows = db ? await db.select().from(adminAuditEvents).orderBy(desc(adminAuditEvents.createdAt)).limit(8) : state.audit.slice(0, 8); return res.json({ actor: { ...actor(req), role }, navigation: Object.entries(rolePermissions[role]).filter(([, allowed]) => allowed).map(([key]) => key), metrics: { totalProducts: products.length, activeProducts: products.filter((item) => item.status === "active").length, lowStock: products.filter((item) => item.stock > 0 && item.stock < 5).length, outOfStock: products.filter((item) => item.stock <= 0).length, activePromotions: promotions.filter((item) => item.status === "active").length, pendingOrders: orderRows.filter((item) => item.fulfillmentStatus === "pending").length }, recentOrders: orderRows, recentAudit: auditRows, counts: { products: products.length, categories: categories.length, promotions: promotions.length, banners: banners.length } }); } catch (error) { next(error); } });

  app.get("/api/admin/products", guard("products"), async (req, res, next) => { try { const query = String(req.query.q ?? "").trim().toLowerCase(); const status = String(req.query.status ?? ""); const items = (await productsSnapshot()).filter((item) => (!query || `${item.name} ${item.slug} ${item.category}`.toLowerCase().includes(query)) && (!status || item.status === status)); res.json({ items }); } catch (error) { next(error); } });
  app.post("/api/admin/products", guard("products"), async (req, res, next) => { try { if (adminRole(req) === "staff") return res.status(403).json({ error: { code: "FORBIDDEN", message: "Staff can update existing products but cannot create them." } }); const input = parseBody(productSchema, req.body); await validateCategoryReference(input.category); const product: AdminProduct = { ...input, id: id("p"), availability: availability(input.stock) }; const existing = (await productsSnapshot()).some((item) => item.slug === product.slug); if (existing) return res.status(409).json({ error: { code: "SLUG_EXISTS", message: "A product with this slug already exists." } }); const db = await getDb(); if (db) await db.insert(catalogProducts).values(dbProductValues(product)); else state.products.unshift(product); await audit(req, actor(req), "product.created", "product", product.id, { name: product.name, pricePkr: product.pricePkr, stock: product.stock }); res.status(201).json({ item: product }); } catch (error) { next(error); } });
  app.patch("/api/admin/products/:id", guard("products"), async (req, res, next) => { try { const current = (await productsSnapshot()).find((item) => item.id === String(req.params.id)); if (!current) return res.status(404).json({ error: { code: "NOT_FOUND", message: "Product was not found." } }); if (adminRole(req) === "staff" && Object.keys(req.body ?? {}).some((key) => !["description", "images", "tags", "featured", "status"].includes(key))) return res.status(403).json({ error: { code: "FORBIDDEN", message: "Staff cannot change product identity, pricing, category, or stock from this panel." } }); const input = parseBody(productSchema.partial(), { ...current, ...req.body }); await validateCategoryReference(input.category ?? current.category); const product = { ...current, ...input, availability: availability(input.stock ?? current.stock) }; if (product.slug !== current.slug && (await productsSnapshot()).some((item) => item.id !== product.id && item.slug === product.slug)) return res.status(409).json({ error: { code: "SLUG_EXISTS", message: "A product with this slug already exists." } }); const db = await getDb(); if (db) await db.update(catalogProducts).set(dbProductValues(product)).where(eq(catalogProducts.productKey, product.id)); else state.products = state.products.map((item) => item.id === product.id ? product : item); await audit(req, actor(req), "product.updated", "product", product.id, req.body ?? {}); res.json({ item: product }); } catch (error) { next(error); } });
  app.delete("/api/admin/products/:id", guard("products"), async (req, res, next) => { try { if (adminRole(req) === "staff") return res.status(403).json({ error: { code: "FORBIDDEN", message: "Staff cannot archive products." } }); const productId = String(req.params.id); if (!(await productsSnapshot()).some((item) => item.id === productId)) return res.status(404).json({ error: { code: "NOT_FOUND", message: "Product was not found." } }); const db = await getDb(); if (db) await db.update(catalogProducts).set({ status: "archived" }).where(eq(catalogProducts.productKey, productId)); else state.products = state.products.map((item) => item.id === productId ? { ...item, status: "archived" } : item); await audit(req, actor(req), "product.archived", "product", productId, { status: "archived" }); res.status(204).end(); } catch (error) { next(error); } });

  app.get("/api/admin/categories", guard("categories"), async (_req, res, next) => { try { res.json({ items: await categoriesSnapshot() }); } catch (error) { next(error); } });
  app.post("/api/admin/categories", guard("categories"), async (req, res, next) => { try { const input = parseBody(categorySchema, req.body); if ((await categoriesSnapshot()).some((item) => item.slug === input.slug)) return res.status(409).json({ error: { code: "SLUG_EXISTS", message: "A category with this slug already exists." } }); const category: AdminCategory = { ...input, id: id("cat") }; const db = await getDb(); if (db) { const [inserted] = await db.insert(adminCategories).values(input).returning({ id: adminCategories.id }); category.id = String(inserted?.id ?? category.id); } else state.categories.push(category); await audit(req, actor(req), "category.created", "category", category.id, input); res.status(201).json({ item: category }); } catch (error) { next(error); } });
  app.patch("/api/admin/categories/:id", guard("categories"), async (req, res, next) => { try { const existing = (await categoriesSnapshot()).find((item) => item.id === String(req.params.id)); if (!existing) return res.status(404).json({ error: { code: "NOT_FOUND", message: "Category was not found." } }); const input = parseBody(categorySchema.partial(), req.body); const item = { ...existing, ...input }; if (item.slug !== existing.slug && (await categoriesSnapshot()).some((row) => row.id !== existing.id && row.slug === item.slug)) return res.status(409).json({ error: { code: "SLUG_EXISTS", message: "A category with this slug already exists." } }); const db = await getDb(); if (db) await db.update(adminCategories).set(input).where(eq(adminCategories.id, Number(String(req.params.id)))); else state.categories = state.categories.map((row) => row.id === item.id ? item : row); await audit(req, actor(req), "category.updated", "category", item.id, input); res.json({ item }); } catch (error) { next(error); } });
  app.delete("/api/admin/categories/:id", guard("categories"), async (req, res, next) => { try { const existing = (await categoriesSnapshot()).find((item) => item.id === String(req.params.id)); if (!existing) return res.status(404).json({ error: { code: "NOT_FOUND", message: "Category was not found." } }); const inUse = (await productsSnapshot()).some((product) => (product.category === existing.slug || product.category.toLowerCase() === existing.name.toLowerCase()) && product.status !== "archived"); if (inUse) return res.status(409).json({ error: { code: "CATEGORY_IN_USE", message: "Reassign products before archiving this category." } }); const db = await getDb(); if (db) await db.update(adminCategories).set({ status: "archived" }).where(eq(adminCategories.id, Number(String(req.params.id)))); else state.categories = state.categories.map((row) => row.id === existing.id ? { ...row, status: "archived" } : row); await audit(req, actor(req), "category.archived", "category", existing.id, { status: "archived" }); res.status(204).end(); } catch (error) { next(error); } });

  app.get("/api/admin/inventory", guard("inventory"), async (_req, res, next) => { try { const products = await productsSnapshot(); const db = await getDb(); const history = db ? await db.select().from(inventoryAdjustments).orderBy(desc(inventoryAdjustments.createdAt)).limit(200) : state.adjustments.slice(0, 200); res.json({ items: products.map((item) => ({ ...item, availableStock: item.stock })), history }); } catch (error) { next(error); } });
  app.post("/api/admin/inventory/adjust", guard("inventory"), async (req, res, next) => { try { const input = parseBody(inventorySchema, req.body); const product = (await productsSnapshot()).find((item) => item.id === input.productKey); if (!product) return res.status(404).json({ error: { code: "NOT_FOUND", message: "Product was not found." } }); const nextStock = product.stock + input.adjustment; if (nextStock < 0) return res.status(409).json({ error: { code: "NEGATIVE_STOCK", message: "Inventory cannot become negative." } }); const db = await getDb(); if (db) { const updated = await db.update(catalogProducts).set({ stock: sql`${catalogProducts.stock} + ${input.adjustment}` }).where(and(eq(catalogProducts.productKey, product.id), sql`${catalogProducts.stock} + ${input.adjustment} >= 0`)).returning({ productKey: catalogProducts.productKey }); if (updated.length !== 1) return res.status(409).json({ error: { code: "STOCK_CONFLICT", message: "Inventory changed before this adjustment could be applied." } }); await db.insert(inventoryAdjustments).values({ productKey: product.id, previousQuantity: product.stock, adjustment: input.adjustment, resultingQuantity: nextStock, reason: input.reason, actorUserId: actor(req).id, requestId: req.res?.locals.requestId }); } else { state.products = state.products.map((item) => item.id === product.id ? { ...item, stock: nextStock, availability: availability(nextStock) } : item); state.adjustments.unshift({ id: id("adjust"), ...input, previousQuantity: product.stock, resultingQuantity: nextStock, actorUserId: actor(req).id, createdAt: new Date().toISOString() }); } await audit(req, actor(req), "inventory.adjusted", "product", product.id, { previousQuantity: product.stock, adjustment: input.adjustment, resultingQuantity: nextStock, reason: input.reason }); res.json({ item: { ...product, stock: nextStock, availability: availability(nextStock) } }); } catch (error) { next(error); } });

  app.get("/api/admin/promotions", guard("promotions"), async (_req, res, next) => { try { res.json({ items: await promotionsSnapshot() }); } catch (error) { next(error); } });
  app.post("/api/admin/promotions", guard("promotions"), async (req, res, next) => { try { const input = parseBody(promotionSchema, req.body); await validatePromotionTarget(input); const item: AdminPromotion = { ...input, status: campaignStatus(input), id: id("promo") }; const db = await getDb(); if (db) { const [inserted] = await db.insert(adminPromotions).values({ ...input, status: item.status, startAt: input.startAt ? new Date(input.startAt) : null, endAt: input.endAt ? new Date(input.endAt) : null }).returning({ id: adminPromotions.id }); item.id = String(inserted?.id ?? item.id); } else state.promotions.unshift(item); await audit(req, actor(req), "promotion.created", "promotion", item.id, input); res.status(201).json({ item }); } catch (error) { next(error); } });
  app.patch("/api/admin/promotions/:id", guard("promotions"), async (req, res, next) => { try { const current = (await promotionsSnapshot()).find((item) => item.id === String(req.params.id)); if (!current) return res.status(404).json({ error: { code: "NOT_FOUND", message: "Promotion was not found." } }); const input = parseBody(campaignPatchSchema, { ...current, ...req.body }); await validatePromotionTarget(input as AdminPromotion); const item: AdminPromotion = { ...current, ...input, status: campaignStatus(input as AdminPromotion) }; const db = await getDb(); if (db) await db.update(adminPromotions).set({ ...input, status: item.status, startAt: input.startAt ? new Date(input.startAt) : null, endAt: input.endAt ? new Date(input.endAt) : null }).where(eq(adminPromotions.id, Number(String(req.params.id)))); else state.promotions = state.promotions.map((row) => row.id === item.id ? item : row); await audit(req, actor(req), `promotion.${item.status === "active" ? "activated" : "updated"}`, "promotion", item.id, input); res.json({ item }); } catch (error) { next(error); } });

  app.get("/api/admin/banners", guard("banners"), async (_req, res, next) => { try { res.json({ items: await bannersSnapshot() }); } catch (error) { next(error); } });
  app.post("/api/admin/banners", guard("banners"), async (req, res, next) => { try { const input = parseBody(bannerSchema, req.body); const item: AdminBanner = { ...input, status: campaignStatus(input), id: id("banner") }; const db = await getDb(); if (db) { const [inserted] = await db.insert(adminBanners).values({ ...input, status: item.status, startAt: input.startAt ? new Date(input.startAt) : null, endAt: input.endAt ? new Date(input.endAt) : null }).returning({ id: adminBanners.id }); item.id = String(inserted?.id ?? item.id); } else state.banners.push(item); await audit(req, actor(req), "banner.created", "banner", item.id, input); res.status(201).json({ item }); } catch (error) { next(error); } });
  app.patch("/api/admin/banners/:id", guard("banners"), async (req, res, next) => { try { const current = (await bannersSnapshot()).find((item) => item.id === String(req.params.id)); if (!current) return res.status(404).json({ error: { code: "NOT_FOUND", message: "Banner was not found." } }); const input = parseBody(bannerSchema.partial(), { ...current, ...req.body }); const item = { ...current, ...input, status: campaignStatus({ status: input.status ?? current.status, startAt: input.startAt ?? current.startAt, endAt: input.endAt ?? current.endAt }) }; const db = await getDb(); if (db) await db.update(adminBanners).set({ ...input, status: item.status, startAt: input.startAt ? new Date(input.startAt) : null, endAt: input.endAt ? new Date(input.endAt) : null }).where(eq(adminBanners.id, Number(String(req.params.id)))); else state.banners = state.banners.map((row) => row.id === item.id ? item : row); await audit(req, actor(req), `banner.${item.status === "active" ? "published" : "updated"}`, "banner", item.id, input); res.json({ item }); } catch (error) { next(error); } });

  app.get("/api/admin/orders", guard("orders"), async (_req, res, next) => { try { const db = await getDb(); const items = db ? await db.select().from(orders).orderBy(desc(orders.createdAt)).limit(200) : []; res.json({ items }); } catch (error) { next(error); } });
  app.patch("/api/admin/orders/:id", guard("orders"), async (req, res, next) => { try { const input = parseBody(orderSchema, req.body); const allowed: Record<string, string[]> = { pending: ["processing", "cancelled"], processing: ["packed", "cancelled"], packed: ["shipped", "cancelled"], shipped: ["delivered"], delivered: [], cancelled: [] }; const db = await getDb(); if (!db) return res.status(404).json({ error: { code: "NO_DATABASE", message: "Order operations require the configured commerce database." } }); const existing = await db.select().from(orders).where(eq(orders.orderNumber, String(req.params.id))).limit(1); if (!existing[0]) return res.status(404).json({ error: { code: "NOT_FOUND", message: "Order was not found." } }); if (!allowed[existing[0].fulfillmentStatus]?.includes(input.fulfillmentStatus)) return res.status(409).json({ error: { code: "INVALID_FULFILLMENT_TRANSITION", message: `Cannot move an order from ${existing[0].fulfillmentStatus} to ${input.fulfillmentStatus}.` } }); await db.update(orders).set({ fulfillmentStatus: input.fulfillmentStatus }).where(eq(orders.orderNumber, String(req.params.id))); await audit(req, actor(req), "order.fulfillment_updated", "order", String(req.params.id), input); res.json({ ok: true }); } catch (error) { next(error); } });
  app.get("/api/admin/customers", guard("customers"), async (_req, res, next) => { try { const db = await getDb(); if (!db) return res.json({ items: [] }); const items = await db.select({ id: users.id, openId: users.openId, email: users.email, name: users.name, role: users.role, createdAt: users.createdAt }).from(users).orderBy(desc(users.createdAt)).limit(200); const orderRows = await db.select({ userId: orders.userId }).from(orders).limit(10000); const orderCounts = new Map<number, number>(); for (const row of orderRows) if (row.userId != null) orderCounts.set(row.userId, (orderCounts.get(row.userId) ?? 0) + 1); res.json({ items: items.map((item) => ({ ...item, orderCount: orderCounts.get(item.id) ?? 0 })) }); } catch (error) { next(error); } });
  app.get("/api/admin/staff", guard("staff"), async (_req, res, next) => { try { const db = await getDb(); const items = db ? await db.select({ id: users.id, openId: users.openId, email: users.email, name: users.name, role: users.role, createdAt: users.createdAt }).from(users).where(sql`${users.role} in ('owner','admin','staff')`).orderBy(desc(users.createdAt)).limit(200) : [{ id: "demo-owner", openId: "demo-owner", email: "owner@local.demo", name: "Demo Owner", role: "owner", createdAt: new Date() }]; res.json({ items }); } catch (error) { next(error); } });
  app.patch("/api/admin/staff/:id", guard("staff"), async (req, res, next) => { try { const input = parseBody(roleSchema, req.body); const db = await getDb(); if (!db) return res.status(404).json({ error: { code: "NO_DATABASE", message: "Staff management requires the configured commerce database." } }); const existing = (await db.select({ role: users.role }).from(users).where(eq(users.id, Number(String(req.params.id)))).limit(1))[0]; if (!existing) return res.status(404).json({ error: { code: "NOT_FOUND", message: "Staff member was not found." } }); if (existing.role === "owner") return res.status(409).json({ error: { code: "OWNER_PROTECTED", message: "The owner role cannot be reassigned from this panel." } }); await db.update(users).set({ role: input.role }).where(eq(users.id, Number(String(req.params.id)))); await audit(req, actor(req), "staff.role_updated", "staff", String(req.params.id), input); res.json({ ok: true }); } catch (error) { next(error); } });
  app.get("/api/admin/audit", guard("audit"), async (req, res, next) => { try { const limit = Math.min(Math.max(Number(req.query.limit ?? 50) || 50, 1), 100); const offset = Math.max(Number(req.query.offset ?? 0) || 0, 0); const action = String(req.query.action ?? "").trim(); const resource = String(req.query.resource ?? "").trim(); const actorRole = String(req.query.actorRole ?? "").trim(); const db = await getDb(); if (db) { const filters = [action ? eq(adminAuditEvents.action, action) : undefined, resource ? eq(adminAuditEvents.resource, resource) : undefined, actorRole ? eq(adminAuditEvents.actorRole, actorRole) : undefined].filter((value): value is NonNullable<typeof value> => Boolean(value)); const items = await db.select().from(adminAuditEvents).where(filters.length ? and(...filters) : undefined).orderBy(desc(adminAuditEvents.createdAt)).limit(limit).offset(offset); return res.json({ items, pagination: { limit, offset, hasMore: items.length === limit } }); } const filtered = state.audit.filter((item) => (!action || item.action === action) && (!resource || item.resource === resource) && (!actorRole || item.actorRole === actorRole)); const items = filtered.slice(offset, offset + limit); res.json({ items, pagination: { limit, offset, hasMore: offset + items.length < filtered.length } }); } catch (error) { next(error); } });
  app.get("/api/admin/settings", guard("settings"), async (_req, res, next) => { try { const db = await getDb(); res.json({ items: [{ key: "workspace", value: "Usamabhanbhro Merchant Studio" }, { key: "environment", value: process.env.APP_ENV ?? "development" }, { key: "persistence", value: db ? "database-backed" : "in-memory demo store" }, { key: "catalog", value: "server-owned catalog snapshot" }, { key: "payments", value: "demo-only; no real transactions" }] }); } catch (error) { next(error); } });
  app.post("/api/admin/media/presign", mediaGuard, async (req, res, next) => { try { const key = String(req.body?.key ?? ""); const contentType = String(req.body?.contentType ?? ""); const size = Number(req.body?.size ?? 0); const result = await createUploadUrl({ key, contentType, size }); await audit(req, actor(req), "media.presigned", "media", key, { contentType, size }); res.status(201).json(result); } catch (error) { next(error); } });
  app.delete("/api/admin/media", mediaGuard, async (req, res, next) => { try { const key = String(req.body?.key ?? ""); const result = await deleteObject(key); await audit(req, actor(req), "media.deleted", "media", key, { key }); res.json(result); } catch (error) { next(error); } });
}
